In [1]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
import os
from google.colab import drive
import re
import random
# 1. Mount Google Drive
print("Mounting Google Drive...")
drive.mount('/content/drive')
print("✅ Drive mounted successfully.")

# 2. Define the base directory for your project inside Drive
# 🔑 IMPORTANT: Change 'YourProject' to the actual folder name in your Drive
DRIVE_DIR = '/content/drive/MyDrive/'

# 3. Create the directory if it doesn't exist (good practice for saving checkpoints)
if not os.path.exists(DRIVE_DIR):
    os.makedirs(DRIVE_DIR)
    print(f"Created directory: {DRIVE_DIR}")
else:
    print(f"Using existing directory: {DRIVE_DIR}")
drive_dir=DRIVE_DIR
project_dir=os.path.join(drive_dir,'LLM_Misconception_Project')
checkpoint_dir=os.path.join(project_dir,'Checkpoints')
utils_dir=os.path.join(project_dir,'utils')

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON


import sys
import os # Make sure to import os if you haven't already

# Assuming drive_dir = '/content/drive/MyDrive/YourProject' has been defined.

# 1. Construct the full path to the directory containing the module
module_directory = os.path.join(drive_dir, 'augment_functions_map39.py')

# 2. Add the DIRECTORY to the system path
# Note: You should add the *directory* that contains the file, not the file itself.
# In this case, since the file is expected to be *inside* the drive_dir,
# you should just append the drive_dir itself, as that's where Python will look.

if drive_dir not in sys.path:
    sys.path.append(utils_dir)
    print(f"✅ Added {utils_dir} to sys.path.")
else:
    print(f"ℹ️ {utils_dir} is already in sys.path.")

# 3. Now you can import the module directly
try:
    import augment_functions_map41 as augment_functions
    print("✅ Successfully imported augment_functions_map37.")
except ImportError as e:
    print(f"❌ Failed to import module: {e}")
    print("Ensure the file 'augment_functions_map35.py' is directly inside the directory specified by drive_dir.")

import numpy as np
import pandas as pd
import torch
from torch import nn
from transformers import AutoTokenizer, AutoModel
from sklearn.preprocessing import LabelEncoder
import sys
import os # We need os for path joining and listdir
import preprocessing_functions
# --- 1. Dependencies and Path Configuration ---
!pip install -U bitsandbytes accelerate peft
!pip install latex2mathml





# --- 3. Initialize Flags and Load DataFrames ---
ANALYSIS = False
analysis = False


# Generate augmented data using your imported function
#augmented_data_set = augment_functions.generate_all_augmented_data(change_cat_prob=0.0)
#augmented_data_set['Original_category'] = augmented_data_set['Category'].apply(lambda x: x[0])


print('Initial data setup and augmentation complete. You are now running with the correct file references.')

Mounting Google Drive...
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Drive mounted successfully.
Using existing directory: /content/drive/MyDrive/
✅ Added /content/drive/MyDrive/LLM_Misconception_Project/utils to sys.path.
Updated Module feb 15
✅ Successfully imported augment_functions_map37.
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.4.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from peft) (5.0.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.3->bitsandbytes) (1.3.5)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->peft) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->peft) (0.22.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Requirement already satisfied: latex2mathml in /usr/local/lib/python3.12/dist-packages (3.78.1)
Initial data setup and augmentation complete. You are now running with the correct file references.

In [2]:
import shutil
import os

# 1. Define your paths
drive_path = '/content/drive/MyDrive/LLM_Misconception_Project'
local_path = '/content/LLM_Misconception_Project'

# 2. Define what to exclude (folders or file patterns)
# You can add specific filenames or entire subfolders here
exclude_patterns = [
    'stage2_explanation_model_dec5.pt',
    'stage2_explanation_model_dec5_restructure_B.pt',
    'stage2_explanation_model_dec5_MISC_ONLY_SUB_B.pt',
    'stage2_explanation_model_dec5_MISC_ONLY_SUB.pt'
]

def ignore_files(dir, files):
    """Internal function to tell copytree what to skip."""
    return [f for f in files if f in exclude_patterns]

# 3. Move the folder
if os.path.exists(drive_path):
    if os.path.exists(local_path):
        shutil.rmtree(local_path)
        print("🗑️ Removed old local copy.")

    # Use the ignore parameter to exclude your patterns
    shutil.copytree(drive_path, local_path, ignore=ignore_files)
    print(f"✅ Project successfully copied to: {local_path}")
else:
    print(f"❌ Error: Could not find the project in Drive at {drive_path}")

# 4. Verify
print("\n--- Local Folder Contents ---")
print(os.listdir(local_path))

# Add scripts to path BEFORE importing custom modules
import sys
if local_path not in sys.path:
    sys.path.insert(0, local_path)

✅ Project successfully copied to: /content/LLM_Misconception_Project

--- Local Folder Contents ---
['.git', 'utils', 'requirements.txt', 'data', 'README.md', 'app.py', 'models', 'notebooks', '.gitignore', 'checkpoints']

In [3]:
import app
app.run_app()

This module has been updated feb 16, /content
📁 Project root: /content/LLM_Misconception_Project
📁 Scripts dir: /content/LLM_Misconception_Project/utils
📁 Models dir: /content/LLM_Misconception_Project/models
✅ Setup complete. No extra path variables, no duplicates.
The module has been updated
🔄 Loading label encoders...
🖥️  Using device: cuda
ℹ️ GPU decorator disabled
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://7f3010a9db808d90eb.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

# Locate Assessment

In [4]:

os.listdir(os.path.join(local_path,'data'))

['Assessment_49.csv',
 'Assessment_28.csv',
 'Assessment_23.csv',
 'Inference_Results_2026-02-09_06-11-33.csv',
 'Inference_Results_2026-02-05_07-33-18.csv',
 'Assessment_16.csv',
 'Assessment_33.csv',
 'Inference_Results_2026-02-15_10-58-50.csv',
 'Assessment_10.csv',
 'Inference_Results_2026-02-09_08-52-40.csv',
 'Assessment_20.csv',
 'Assessment_17.csv',
 'Assessment_35.csv',
 'Inference_Results_2026-03-02_08-36-12.csv',
 'Assessement_46.csv',
 'manually_labeled_output2.csv',
 'Assessment_29.csv',
 'Assessment_1.csv',
 'Assessment_3.csv',
 'Assessment_26.csv',
 'Inference_Results_2026-02-05_04-56-42.csv',
 'Inference_Results_2026-02-06_12-35-22.csv',
 'Assessment_45.csv',
 'Assessment_11.csv',
 'Assessment_6.csv',
 'Assessment_14.csv',
 'likely_other.csv',
 'Inference_Results_2.csv',
 'Inference_Results_2026-02-12_05-41-35.csv',
 'Inference_Results_2026-01-15_07-27-49.csv',
 'Inference_Results_2026-02-14_11-52-21.csv',
 '.gitkeep',
 'Assessment_40.csv',
 'Inference_Results_2026-02-04_07-02-54.csv',
 'Assessment_Wrong_Operation_Val_1.csv',
 'Assessment_50.csv',
 'other_indices.npy',
 'Inference_Results_2026-02-17_08-54-01.csv',
 'Assessment_54.csv',
 'Assessment_53.csv',
 'test.csv',
 'Inference_Results_2026-02-11_13-31-34.csv',
 'Assessment_22.csv',
 'Assessment_5.csv',
 'Assessment_31.csv',
 'Inference_Results_feb4_B.csv',
 'Assessment_12.csv',
 'Assessment_51.csv',
 'manually_labeled_output.csv',
 'Inference_Results_2026-02-09_09-53-01.csv',
 'Inference_Results_2026-01-30_09-16-46.csv',
 'Assessment_2.csv',
 'Assessment_44.csv',
 'Assessment_18.csv',
 'Assessment_other2.csv',
 'other_category_analysis.csv',
 'Assessment_other.csv',
 'Assessment_8.csv',
 'Inference_Results_2026-02-08_08-57-01.csv',
 'train.csv',
 'Inference_Results_2026-01-18_11-01-45.csv',
 'Inference_Results_2026-02-13_11-28-15.csv',
 'Assessment_30.csv',
 'Inference_Results_2026-02-17_07-34-30.csv',
 'other_category_predictions.csv',
 'Inference_Results_feb_4_A.csv',
 'Inference_Results_2026-02-16_12-15-08.csv',
 'Assessment_25.csv',
 'Assessment_9.csv',
 'Assessment_15.csv',
 'Assessment_19.csv',
 'Assessment_21.csv',
 'Inference_Results_2026-02-10_14-57-07.csv',
 'Assessment_47.csv',
 'Inference_Results_2026-02-08_11-46-50.csv',
 'Inference_Results_2026-01-30_07-39-42.csv',
 'Assessment_7.csv',
 'Inference_Results_2026-01-16_05-46-13.csv',
 'Assessment_32.csv',
 'Inference_Results_2026-02-01_09-17-34.csv',
 'Assessment_13.csv',
 'Assessment_39.csv',
 'Assessment_42.csv',
 'other_samples_promoted_to_training.csv',
 'Assessment_24.csv',
 'Inference_Results_2026-02-04_17-58-47.csv',
 'Assessment_52.csv',
 'Inference_Results_2026-02-15_07-18-48.csv',
 'Inference_Results_2026-02-18_07-49-39.csv',
 'Inference_Results_2026-02-14_19-59-24.csv',
 'Assessment_48.csv',
 'Assessment_34.csv',
 'Assessment_Wrong_Operation_1.csv',
 'other_samples_relabeled.csv',
 'Assessment_4.csv',
 'Inference_Results_2026-03-03_12-32-16.csv',
 'Inference_Results_2026-02-03_10-37-41.csv',
 'Assessment_for_app.csv',
 'Inference_Results_1.csv']

# Load Assessment
- load the assessment from local content directory and save in project directory

In [5]:
assessment=pd.read_csv(os.path.join(local_path,'data',    'Inference_Results_2026-03-03_12-32-16.csv'))
assessment.to_csv(os.path.join(project_dir,'data',   'Inference_Results_2026-03-03_12-32-16.csv'),index=False)

assessment['Misconception']=assessment['predicted_misconception_all']
assessment['Category']=assessment['predicted_category']
assessment['Category']=assessment['Category'].apply(lambda x: [x])
assessment

,Unnamed: 0,QuestionText,StudentExplanation,Category,Misconception,MC_Answer,function,problem_type,Original_Index,Mathematical_Context,context_values,StudentExplanation_Original,Mathematical_Context_Reduced,extracted_sa,actual_correct_answer,Correctness,predicted_category,predicted_misconception_all,predicted_misconception_top,predicted_correctness
0,0,compute \(\frac{1}{3} \div 9\). Simplify if ne...,flip and multiply . its N1/F1xN3_SwapDividend_...,[True_Correct],['No Misconception'],\( \frac{1}{27} \),NaN,1,1,| SA:1/27 | NUM_COUNT:3 | FRAC_COUNT:1 | N1:1...,"['1/27', '9/3', '3', '3/9', '1/3']",flip and multiply . its 1/3 X 1/9 =1/27,F1_NUM_LT_DEN:TRUE | ANSWER_HAS_FRACTION:TRUE ...,1/27,['1/27'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
1,1,Dots have been arranged in these patterns: [Im...,I really don't know,[False_Neither],['Other'],\( 22 \),NaN,2,12,| PATTERN_N:6 | SEQ_FIRST_TERM:6 | SEQ_COMMON...,"['26', '36', '2', '6', '10', '14', '18', '22',...",I really don't know,ANSWER_IS_CORRECT:FALSE | ANSWER_MATCHES_NEXT_...,22,['26'],Incorrect,False_Neither,['Other'],Other,Incorrect
2,2,Calculate \(\frac{3}{4} \times 6\). simplify i...,its F1_NUM x WHOLE_NUMBER=F1xN3_UNSIM so F1xN3...,[True_Correct],['No Misconception'],\( \frac{9}{2} \),NaN,3,5,| SA:9/2 | NUM_COUNT:3 | FRAC_COUNT:1 | N1:3 ...,"['18/4', '18/24', '3/24', '1/8', '8/1', '9/2',...",its 3x6=18 over 4 so 18/4 which simplifies to 9/2,F1_NUM_LT_DEN:TRUE | ANSWER_HAS_FRACTION:TRUE ...,9/2,"['9/2', '4 1/2']",Correct,True_Correct,['No Misconception'],No Misconception,Correct
3,3,A box contains \( 120 \) counters. The counter...,if FRACTION are red you would multiply the tot...,[False_Correct],['None'],\( \frac{360}{5} \),NaN,4,2,| SA:360/5 | NUM_COUNT:3 | FRAC_COUNT:1 | ALL...,"['120/5', '120/3', '24', '240', '600', '360/5'...",if 3/5 are red you would multiply the total ti...,NaN,360/5,['72'],Incorrect,False_Correct,['None'],No Misconception,Incorrect
4,4,\( \frac{1}{2} + \frac{3}{12} = \),the lcd is F1+F2_LCD_VALUE so add the tops F2_...,[False_Misconception],"['Denominator-only_change', 'Incomplete']",\( \frac{4}{12} \),self_typed,5,17,| SA:4/12 | NUM_COUNT:4 | FRAC_COUNT:2 | N1:1...,"['9/12', '3/4', '9/24', '3/8', '4/14', '2/7', ...",the lcd is 12 so add the tops 1+3=4. 4/12,F1_NUM_LT_DEN:TRUE | F2_NUM_LT_DEN:TRUE | ANSW...,4/12,['3/4'],Incorrect,False_Misconception,"['Denominator-only_change', 'Incomplete']",Denominator-only_change,Incorrect
5,5,Identify the bigger number. Options: 6 and 6.002,ACTUAL_LARGEST_VALUE is the longer number whic...,[True_Misconception],['Longer_is_bigger'],\( 6.002 \),self_typed,7,15,| SA:6.002 | NUM_COUNT:2 | FRAC_COUNT:0 | N1:...,"['6', '6.002']",6.002 is the longer number which are bigger th...,ANSWER_MATCHES_HIGHEST_NON_ZERO_DIGIT:True | A...,6.002,['6.002'],Correct,True_Misconception,['Longer_is_bigger'],Longer_is_bigger,Correct
6,6,It takes \( 3 \) people a total of \( 192 \) h...,MULTIPLIER is the multiplier. N3/MULTIPLIER is...,[True_Correct],['No Misconception'],\( 48 \),NaN,8,13,| SA:48 | NUM_COUNT:3 | FRAC_COUNT:0 | N1:3 |...,"['15', '36', '195', '576', '64', '204', '2304'...",4 is the multiplier. 192/4 is 48,ANSWER_HAS_FRACTION:FALSE,48,['48'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
7,7,Lupita has 2/3 of a whole piece of cake. Mooki...,Since Mookie consumes less than lupita you hav...,[False_Misconception],['None'],\( 2 \),NaN,9,9,| SA:2 | NUM_COUNT:3 | FRAC_COUNT:2 | N1:1 | ...,"['2/9', '1/3', '6/3', '2', '3/6']",Since Mookie consumes less than lupita you hav...,F1_NUM_LT_DEN:TRUE | F2_NUM_LT_DEN:TRUE | ANSW...,2,['2/9'],Incorrect,False_Misconception,['None'],Division,Incorrect
8,8,The probability of an event occurring is \( 0....,its PERCENT_GREATER_THAN_50% so its only COMP_...,[True_Correct],['No Misconception'],Likely,NaN,10,14,| SA:Likely | NUM_COUNT:1 | FRAC_COUNT:0 | N1...,"['Likely', 'Unlikely', 'Impossible', 'Certain']",its 90% so its only 10 away from certain.,N1_IS_GREATER_THAN_0_5:True | N1_IS_LESS_THAN_...,Likely,['Likely'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
9,9,This is part of a regular polygon. How many si...,I thought it was 6 because N1 goes into 720 wh...,[False_Misconception],['Interior'],\( 9 \),NaN,11,10,| SA:9 | NUM_COUNT:1 | FRAC_COUNT:0 | N1:144 ...,"['1', '2.5', '3', '4', '9', '10', '11', '12']",I thought it was 6 because 144 goes into 720 w...,ANSWER_HAS_FRACTION:FALSE,9,['10'],Incorrect,False_Misconception,['Interior'],Interior,Incorrect
10,10,What number belongs in the box? \( (-8)-(-5)= ...,use keep change change -8++N2_OPP=-3,[True_Correct],['No Misconception'],\( -3 \),NaN,12,11,| SA:-3 | NUM_COUNT:2 | FRAC_COUNT:0 | N1:-8 ...,"['-13', '-3', '3', '13']",use keep change change -8++5=-3,ANSWER_HAS_FRACTION:FALSE,-3,['-3'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
11,11,\( 2 y=24 \) What is the value of \( y \) ?,divide both sides by COEFFICIENT to get RIGHT_...,[True_Correct],['No Misconception'],\( 12 \),NaN,13,4,| SA:12 | NUM_COUNT:2 | FRAC_COUNT:0 | N1:2 |...,"['26', '-22', '48', '4', '12']",divide both sides by 2 to get 24/2=12,ANSWER_HAS_FRACTION:FALSE,12,['12'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
12,12,\( \frac{A}{10}=\frac{9}{15} \) What is the va...,DEN_LEFT - DEN_RIGHT=ADDITIVE_PART1 so you add...,[False_Misconception],['Additive'],\( 14 \),NaN,14,3,| SA:14 | NUM_COUNT:3 | FRAC_COUNT:1 | N1:10 ...,"['27/45', '3/45', '1/15', '15/1', '45/5', '9/1...",10-15=-5 so you add 5 to the 9 to get 14.,F1_NUM_LT_DEN:TRUE | ANSWER_HAS_FRACTION:FALSE,14,['6'],Incorrect,False_Misconception,['Additive'],Additive,Incorrect
13,13,What fraction of the shape is not shaded? Give...,TOTAL-N1=TOTAL_MINUS_N1 which is the non shade...,[True_Correct],['No Misconception'],\( \frac{1}{3} \),NaN,15,0,| SA:1/3 | NUM_COUNT:2 | FRAC_COUNT:0 | N1:6 ...,"['6/9', '2/3', '6/3', '2', '3/6', '1/2', '3/9'...",9-6=3 which is the non shaded part so the tota...,N1_IS_GREATER_THAN_0_5:True | N1_IS_LESS_THAN_...,1/3,['1/3'],Correct,True_Correct,['No Misconception'],No Misconception,Correct

In [6]:
for ind, row in assessment.iterrows():
  print(row['QuestionText'])
  print(row['StudentExplanation'])
  print(row['MC_Answer'])
  print('\tPredicted Misconception: ',row['Misconception'])
  print('\tPredicted Category: ',row['Category'])
  print()
  #print(row['Mathematical_Context'])
  print('*'*10,'New','*'*15)

compute \(\frac{1}{3} \div 9\). Simplify if necessary.
flip and multiply . its N1/F1xN3_SwapDividend_MIXEDX N3_INVERTED =CorrectAnswer_UNSIM_MIXED
\( \frac{1}{27} \)
	Predicted Misconception:  ['No Misconception']
	Predicted Category:  ['True_Correct']

********** New ***************
Dots have been arranged in these patterns: [Image: Pattern 1 consists of 6 dots, Pattern 2 consists of 10 dots, Pattern 3 consists of 14 dots and Pattern 4 consists of 18 dots] How many dots would there be in Pattern \( 6 \) ?
I really don't know
\( 22 \)
	Predicted Misconception:  ['Other']
	Predicted Category:  ['False_Neither']

********** New ***************
Calculate \(\frac{3}{4} \times 6\). simplify if necessary.
its F1_NUM x WHOLE_NUMBER=F1xN3_UNSIM so F1xN3_UNSIM which simplifies to F1xN3_SIM
\( \frac{9}{2} \)
	Predicted Misconception:  ['No Misconception']
	Predicted Category:  ['True_Correct']

********** New ***************
A box contains \( 120 \) counters. The counters are red or blue. \( \frac{3}{5} \) of the counters are red. How many red counters are there?
if FRACTION are red you would multiply the total times FRACTION. FRACTION_NUMERATOR/5X120 is NUM_TIMES_WHOLE_DIV_DEN_UNSIM
\( \frac{360}{5} \)
	Predicted Misconception:  ['None']
	Predicted Category:  ['False_Correct']

********** New ***************
\( \frac{1}{2} + \frac{3}{12} = \)
the lcd is F1+F2_LCD_VALUE so add the tops F2_ORIG_NUM + F1_ORIG_NUM=F1_DEN. F1+F2_DENOM_ONLY_CHANGE
\( \frac{4}{12} \)
	Predicted Misconception:  ['Denominator-only_change', 'Incomplete']
	Predicted Category:  ['False_Misconception']

********** New ***************
Identify the bigger number. Options: 6 and 6.002
ACTUAL_LARGEST_VALUE is the longer number which are bigger than shorter
\( 6.002 \)
	Predicted Misconception:  ['Longer_is_bigger']
	Predicted Category:  ['True_Misconception']

********** New ***************
It takes \( 3 \) people a total of \( 192 \) hours to build a wall. How long would it take if \( 12 \) people built the same wall?
MULTIPLIER is the multiplier. N3/MULTIPLIER is CORRECT_ANSWER
\( 48 \)
	Predicted Misconception:  ['No Misconception']
	Predicted Category:  ['True_Correct']

********** New ***************
Lupita has 2/3 of a whole piece of cake. Mookie consumes 1/3 of this piece. What fraction of the whole cake has Mookie consumed?
Since Mookie consumes less than lupita you have to divide to make the number smaller. F2/F1_SUBTRACT_F2_SIMPLIFIED is F1_DIV_F2_SIMPLIFIED/N3 x N3/N1 is F1_DIV_F2_SIMPLIFIED.
\( 2 \)
	Predicted Misconception:  ['None']
	Predicted Category:  ['False_Misconception']

********** New ***************
The probability of an event occurring is \( 0.9 \). Which of the following most accurately describes the likelihood of the event occurring?
its PERCENT_GREATER_THAN_50% so its only COMP_PERCENT_LESS_THAN_50 away from certain.
Likely
	Predicted Misconception:  ['No Misconception']
	Predicted Category:  ['True_Correct']

********** New ***************
This is part of a regular polygon. How many sides does it have? [Image: A diagram showing an obtuse angle labelled 144 degrees]
I thought it was 6 because N1 goes into 720 which is a hexagon. But i guess SA.
\( 9 \)
	Predicted Misconception:  ['Interior']
	Predicted Category:  ['False_Misconception']

********** New ***************
What number belongs in the box? \( (-8)-(-5)= \square\)
use keep change change -8++N2_OPP=-3
\( -3 \)
	Predicted Misconception:  ['No Misconception']
	Predicted Category:  ['True_Correct']

********** New ***************
\( 2 y=24 \) What is the value of \( y \) ?
divide both sides by COEFFICIENT to get RIGHT_SIDE/COEFFICIENT=N2divN1
\( 12 \)
	Predicted Misconception:  ['No Misconception']
	Predicted Category:  ['True_Correct']

********** New ***************
\( \frac{A}{10}=\frac{9}{15} \) What is the value of \( A \) ?
DEN_LEFT - DEN_RIGHT=ADDITIVE_PART1 so you add F1_DEN to the NUM_RIGHT to get ADDITIVE_ANSWER.
\( 14 \)
	Predicted Misconception:  ['Additive']
	Predicted Category:  ['False_Misconception']

********** New ***************
What fraction of the shape is not shaded? Give your answer in its simplest form. [Image: A triangle split into 9 equal smaller triangles. 6 of them are shaded.]
TOTAL-N1=TOTAL_MINUS_N1 which is the non shaded part so the total is TOTAL . so COMP_ANSWER_UNSIM which reduces to SA
\( \frac{1}{3} \)
	Predicted Misconception:  ['No Misconception']
	Predicted Category:  ['True_Correct']

********** New ***************

# Make Alterations and Save Assessment To Drive

In [8]:
assessment.at[3,'Misconception']=['Incomplete']
assessment.at[7,'Misconception']=['Division']

assessment

,Unnamed: 0,QuestionText,StudentExplanation,Category,Misconception,MC_Answer,function,problem_type,Original_Index,Mathematical_Context,context_values,StudentExplanation_Original,Mathematical_Context_Reduced,extracted_sa,actual_correct_answer,Correctness,predicted_category,predicted_misconception_all,predicted_misconception_top,predicted_correctness
0,0,compute \(\frac{1}{3} \div 9\). Simplify if ne...,flip and multiply . its N1/F1xN3_SwapDividend_...,[True_Correct],['No Misconception'],\( \frac{1}{27} \),NaN,1,1,| SA:1/27 | NUM_COUNT:3 | FRAC_COUNT:1 | N1:1...,"['1/27', '9/3', '3', '3/9', '1/3']",flip and multiply . its 1/3 X 1/9 =1/27,F1_NUM_LT_DEN:TRUE | ANSWER_HAS_FRACTION:TRUE ...,1/27,['1/27'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
1,1,Dots have been arranged in these patterns: [Im...,I really don't know,[False_Neither],['Other'],\( 22 \),NaN,2,12,| PATTERN_N:6 | SEQ_FIRST_TERM:6 | SEQ_COMMON...,"['26', '36', '2', '6', '10', '14', '18', '22',...",I really don't know,ANSWER_IS_CORRECT:FALSE | ANSWER_MATCHES_NEXT_...,22,['26'],Incorrect,False_Neither,['Other'],Other,Incorrect
2,2,Calculate \(\frac{3}{4} \times 6\). simplify i...,its F1_NUM x WHOLE_NUMBER=F1xN3_UNSIM so F1xN3...,[True_Correct],['No Misconception'],\( \frac{9}{2} \),NaN,3,5,| SA:9/2 | NUM_COUNT:3 | FRAC_COUNT:1 | N1:3 ...,"['18/4', '18/24', '3/24', '1/8', '8/1', '9/2',...",its 3x6=18 over 4 so 18/4 which simplifies to 9/2,F1_NUM_LT_DEN:TRUE | ANSWER_HAS_FRACTION:TRUE ...,9/2,"['9/2', '4 1/2']",Correct,True_Correct,['No Misconception'],No Misconception,Correct
3,3,A box contains \( 120 \) counters. The counter...,if FRACTION are red you would multiply the tot...,[False_Correct],[Incomplete],\( \frac{360}{5} \),NaN,4,2,| SA:360/5 | NUM_COUNT:3 | FRAC_COUNT:1 | ALL...,"['120/5', '120/3', '24', '240', '600', '360/5'...",if 3/5 are red you would multiply the total ti...,NaN,360/5,['72'],Incorrect,False_Correct,['None'],No Misconception,Incorrect
4,4,\( \frac{1}{2} + \frac{3}{12} = \),the lcd is F1+F2_LCD_VALUE so add the tops F2_...,[False_Misconception],"['Denominator-only_change', 'Incomplete']",\( \frac{4}{12} \),self_typed,5,17,| SA:4/12 | NUM_COUNT:4 | FRAC_COUNT:2 | N1:1...,"['9/12', '3/4', '9/24', '3/8', '4/14', '2/7', ...",the lcd is 12 so add the tops 1+3=4. 4/12,F1_NUM_LT_DEN:TRUE | F2_NUM_LT_DEN:TRUE | ANSW...,4/12,['3/4'],Incorrect,False_Misconception,"['Denominator-only_change', 'Incomplete']",Denominator-only_change,Incorrect
5,5,Identify the bigger number. Options: 6 and 6.002,ACTUAL_LARGEST_VALUE is the longer number whic...,[True_Misconception],['Longer_is_bigger'],\( 6.002 \),self_typed,7,15,| SA:6.002 | NUM_COUNT:2 | FRAC_COUNT:0 | N1:...,"['6', '6.002']",6.002 is the longer number which are bigger th...,ANSWER_MATCHES_HIGHEST_NON_ZERO_DIGIT:True | A...,6.002,['6.002'],Correct,True_Misconception,['Longer_is_bigger'],Longer_is_bigger,Correct
6,6,It takes \( 3 \) people a total of \( 192 \) h...,MULTIPLIER is the multiplier. N3/MULTIPLIER is...,[True_Correct],['No Misconception'],\( 48 \),NaN,8,13,| SA:48 | NUM_COUNT:3 | FRAC_COUNT:0 | N1:3 |...,"['15', '36', '195', '576', '64', '204', '2304'...",4 is the multiplier. 192/4 is 48,ANSWER_HAS_FRACTION:FALSE,48,['48'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
7,7,Lupita has 2/3 of a whole piece of cake. Mooki...,Since Mookie consumes less than lupita you hav...,[False_Misconception],[Division],\( 2 \),NaN,9,9,| SA:2 | NUM_COUNT:3 | FRAC_COUNT:2 | N1:1 | ...,"['2/9', '1/3', '6/3', '2', '3/6']",Since Mookie consumes less than lupita you hav...,F1_NUM_LT_DEN:TRUE | F2_NUM_LT_DEN:TRUE | ANSW...,2,['2/9'],Incorrect,False_Misconception,['None'],Division,Incorrect
8,8,The probability of an event occurring is \( 0....,its PERCENT_GREATER_THAN_50% so its only COMP_...,[True_Correct],['No Misconception'],Likely,NaN,10,14,| SA:Likely | NUM_COUNT:1 | FRAC_COUNT:0 | N1...,"['Likely', 'Unlikely', 'Impossible', 'Certain']",its 90% so its only 10 away from certain.,N1_IS_GREATER_THAN_0_5:True | N1_IS_LESS_THAN_...,Likely,['Likely'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
9,9,This is part of a regular polygon. How many si...,I thought it was 6 because N1 goes into 720 wh...,[False_Misconception],['Interior'],\( 9 \),NaN,11,10,| SA:9 | NUM_COUNT:1 | FRAC_COUNT:0 | N1:144 ...,"['1', '2.5', '3', '4', '9', '10', '11', '12']",I thought it was 6 because 144 goes into 720 w...,ANSWER_HAS_FRACTION:FALSE,9,['10'],Incorrect,False_Misconception,['Interior'],Interior,Incorrect
10,10,What number belongs in the box? \( (-8)-(-5)= ...,use keep change change -8++N2_OPP=-3,[True_Correct],['No Misconception'],\( -3 \),NaN,12,11,| SA:-3 | NUM_COUNT:2 | FRAC_COUNT:0 | N1:-8 ...,"['-13', '-3', '3', '13']",use keep change change -8++5=-3,ANSWER_HAS_FRACTION:FALSE,-3,['-3'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
11,11,\( 2 y=24 \) What is the value of \( y \) ?,divide both sides by COEFFICIENT to get RIGHT_...,[True_Correct],['No Misconception'],\( 12 \),NaN,13,4,| SA:12 | NUM_COUNT:2 | FRAC_COUNT:0 | N1:2 |...,"['26', '-22', '48', '4', '12']",divide both sides by 2 to get 24/2=12,ANSWER_HAS_FRACTION:FALSE,12,['12'],Correct,True_Correct,['No Misconception'],No Misconception,Correct
12,12,\( \frac{A}{10}=\frac{9}{15} \) What is the va...,DEN_LEFT - DEN_RIGHT=ADDITIVE_PART1 so you add...,[False_Misconception],['Additive'],\( 14 \),NaN,14,3,| SA:14 | NUM_COUNT:3 | FRAC_COUNT:1 | N1:10 ...,"['27/45', '3/45', '1/15', '15/1', '45/5', '9/1...",10-15=-5 so you add 5 to the 9 to get 14.,F1_NUM_LT_DEN:TRUE | ANSWER_HAS_FRACTION:FALSE,14,['6'],Incorrect,False_Misconception,['Additive'],Additive,Incorrect
13,13,What fraction of the shape is not shaded? Give...,TOTAL-N1=TOTAL_MINUS_N1 which is the non shade...,[True_Correct],['No Misconception'],\( \frac{1}{3} \),NaN,15,0,| SA:1/3 | NUM_COUNT:2 | FRAC_COUNT:0 | N1:6 ...,"['6/9', '2/3', '6/3', '2', '3/6', '1/2', '3/9'...",9-6=3 which is the non shaded part so the tota...,N1_IS_GREATER_THAN_0_5:True | N1_IS_LESS_THAN_...,1/3,['1/3'],Correct,True_Correct,['No Misconception'],No Misconception,Correct

In [9]:
assessment['function']='self_typed'
assessment['StudentExplanationSubbed']=assessment['StudentExplanation']
assessment['StudentExplanation']=assessment['StudentExplanation_Original']

assessment[['QuestionText', 'StudentExplanation', 'Category', 'Misconception',
       'MC_Answer', 'function', 'problem_type'
       ]].to_csv(os.path.join(project_dir,'data','Assessment_56.csv'),index=False)